variants:
  select: "universal"
ports:
  - name: libsdl2
  - name: sdl12-compat
  - name: libsdl_mixer
  - name: glew
  - name: libpng
# Fluidsynth universal builds are currently broken because of a Portaudio failure
# https://trac.macports.org/ticket/71481
#  - name: fluidsynth
  - name: libogg
  - name: mpg123
  - name: flac
  - name: physfs
  - name: ninja
