name: Package - macOS

on:
  #push:
  #  branches: [ master ]

  #pull_request:
  #  branches: [ master ]

  workflow_dispatch:

  workflow_call:

jobs:
  macos:
    name: macOS
    runs-on: macos-latest
    strategy:
      matrix:
        build:
          - d1
          - d2

    steps:
      - uses: melusina-org/setup-macports@v1

      - name: Clone repository
        uses: actions/checkout@v6
      - name: Fetch tags
        run: git fetch --tags

      - name: Install library dependencies
        run: port install libsdl2 sdl12-compat physfs glew libogg mpg123 flac fluidsynth ninja

      - name: Build and package
        run: |
          cd ${{ matrix.build }}
          echo "::group::Configure"
          cmake -B build -G Ninja -DSDLMIXER=OFF -DCMAKE_BUILD_TYPE=RelWithDebInfo
          echo "::endgroup::"
          echo "::group::Build"
          cmake --build build
          echo "::endgroup::"
          echo "::group::Package"
          cd build && cpack -G Bundle
          echo "::endgroup::"

      - name: Store artifact
        uses: actions/upload-artifact@v7
        with:
          name: macos-arm
          path: "*.dmg"
