name: Package - macOS - arm

on:
  #push:
  #  branches: [ master ]

  #pull_request:
  #  branches: [ master ]

  workflow_dispatch:

  workflow_call:

jobs:
  macos:
    name: macOS Apps
    runs-on: macos-14
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Fetch tags
        run: git fetch --tags

      - name: Install build dependencies
        run: brew install --formula dylibbundler

      - name: Install library dependencies
        run: brew install --formula sdl2 sdl12-compat physfs glew libogg mpg123 flac fluid-synth ninja

      - name: Configure
        run: cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=RelWithDebInfo

      - name: Build
        run: cmake --build build

      - name: Package
        run: cd build && cpack -G Bundle && ls -la
