name: macOS

on:
  #push:
  #  branches: [ master ]

  #pull_request:
  #  branches: [ master ]

  workflow_dispatch:

  workflow_call:

jobs:
  macos:
    name: macOS ${{ matrix.build.name }}
    runs-on: macos-latest
    strategy:
      matrix:
        build:
          - dir: d1
            name: d1x-redux 
          - dir: d2
            name: d2x-redux

    steps:
      - name: Clone repository
        uses: actions/checkout@v6

      - name: Set up MacPorts
        uses: melusina-org/setup-macports@v1
        with:
          parameters: .github/parameters/setup-macports.yaml

      - name: Fetch tags
        run: git fetch --tags

      - name: Build and package
        run: |
          cd ${{ matrix.build.dir }}
          echo "::group::Configure"
          cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=RelWithDebInfo
          echo "::endgroup::"
          echo "::group::Build"
          cmake --build build
          echo "::endgroup::"
          echo "::group::Package"
          cd build && cpack -G Bundle
          echo "::endgroup::"

      - name: Store artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.build.name }}-macos-universal.zip
          path: "${{ matrix.build.dir }}/build/*.dmg"
          if-no-files-found: error
